USE [master]
GO

/****** Object:  Database [planetario]    Script Date: 9/11/2019 19:20:53 ******/
CREATE DATABASE [planetario]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [planetario].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [planetario] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [planetario] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [planetario] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [planetario] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [planetario] SET ARITHABORT OFF 
GO

ALTER DATABASE [planetario] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [planetario] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [planetario] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [planetario] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [planetario] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [planetario] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [planetario] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [planetario] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [planetario] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [planetario] SET  DISABLE_BROKER 
GO

ALTER DATABASE [planetario] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [planetario] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [planetario] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [planetario] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [planetario] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [planetario] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [planetario] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [planetario] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [planetario] SET  MULTI_USER 
GO

ALTER DATABASE [planetario] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [planetario] SET DB_CHAINING OFF 
GO

ALTER DATABASE [planetario] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [planetario] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [planetario] SET  READ_WRITE 
